### ISSUE TITLE
We need a option to hide/remove possibleLimits button

### ISSUE THREAD

**Issue by KaziMahbuburRahman** [0nahid/rc-pagination#1]
Hello Dev, 
Thanks for this awesome package.
It will be great if you add a option to hide/remove the possibleLimits button so that we can hide this button from the users if we want.
![411207501_873829254487181_4280640318016668554_n](https://github.com/0nahid/rc-pagination/assets/63844626/5c2a4dd5-2b08-44a7-beab-b9d3622a7a1f)

**Comment by 0nahid** [comment]
```
      <Pagination
        possibleLimits={[7]}
      />
```

Just pass a single number of how many data you wants to load in your application, it will not shown
like this
![image](https://github.com/0nahid/rc-pagination/assets/41489906/351eedb3-c918-4758-bf6b-e520bf89363b)
